# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 08:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 17, 16, 22, 14, 819925)),
        ),
    ]
