# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 08:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0002_auto_20170217_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='post_date',
        ),
        migrations.AddField(
            model_name='article',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 17, 16, 23, 22, 168750)),
        ),
    ]
